### PR TITLE
fix: add recursive argument and code to add-license-headers

### PR DESCRIPTION
**Pull request by klmcadams**
Add recursive argument and code to the add-license-headers hook. By default, the recursive method will be used to check the headers in the files. For large repositories that break with recursion, add the "--non_recursive_file_check" argument to the hook in the .pre-commit-config.yaml file

### CODE REVIEW

**Comment by klmcadams** [comment]
@RobPasMue, another option instead of relying on the person to add the argument would be either doing a try/except around the recursive code:

```
try:
   changed_headers = recursive_file_check(changed_headers, parser, values, proj, missing_headers, 0)
except RecursionError:
    changed_headers = non_recursive_file_check(changed_headers, parser, values, proj, missing_headers)
```

or check the length of the files array passed in from pre-commit. The recursion limit to python is 995, and the repository that was running it on all its files had 5000 files. 

```
if len(files) <= 995:
    changed_headers = recursive_file_check(changed_headers, parser, values, proj, missing_headers, 0)
else:
    changed_headers = non_recursive_file_check(changed_headers, parser, values, proj, missing_headers)
```

Let me know what you think!

**Comment by RobPasMue** [comment]
Second approach is good - that would get rid of the flag. Thanks @klmcadams!

**Comment by RobPasMue** [comment]
Even better.. why not use the recursion limit?

```import sys

if len(files) <= (sys.getrecursionlimit() - 2):
    ...
else:
    ...
```

Give it a buffer of 2 at least

**Review by RobPasMue — APPROVED** [review]
LGTM! This will require a new release :)

**Pull request merged**
