### PR TITLE
fix: line length over 79 chars

### PR DESCRIPTION
**Pull request by RobPasMue**
Many libraries may not have configured their line length to be 88, 100 etc. and use the default 79 chars for ``flake8``. In those cases, the hook fails. Adapting line length to fulfil 79 chars reqs.

### CODE REVIEW

**Comment by RobPasMue** [comment]
I'm not sure if we should merge this or not though - because the official MIT License text is formatted originally as you already have it. We might just have to let people know that they have to accept larger line lengths. TBDiscussed - @ansys/pyansys-core

**Comment by SMoraisAnsys** [comment]
> I'm not sure if we should merge this or not though - because the official MIT License text is formatted originally as you already have it. We might just have to let people know that they have to accept larger line lengths. TBDiscussed - @ansys/pyansys-core

I do agree with notifying people about that. Could it be possible to have already (re)formatted licenses that are compliant with frequently used line length (e.g. 80, 100 and 120) and let people chose which file to use according to their standard ?

**Comment by RobPasMue** [comment]
That's my point... The official MIT license text is formatted as it originally was in this PR (and not the way I formatted it after the commit). My gut feeling is that we should just take the official text with its formatting - rather than providing versions of the same file in different line lengths. Nonetheless I'm up for discussion. The main problem is that the line in question:

```console
# The above copyright notice and this permission notice shall be included in all
```

Surpasses the 80char limit by 1 - and it is only due to the initial "# " - that's why the original MIT License is compliant with 80 char limit (it would only have 79). We are right at the limit and flake8 complains 😄

**Comment by SMoraisAnsys** [comment]
I agree with your proposition and would prefer to configure flake8 max length than reformat the MIT license.
My previous answer goal was to find a solution that might suit conservative maintainers on the character limit :)

**Comment by RobPasMue** [comment]
Let's bring the topic later today in our weekly meeting @SMoraisAnsys 😄

**Comment by klmcadams** [comment]
In the meeting, it was concluded that we would keep the MIT.txt file the same

**Pull request closed without merging**
