### PR TITLE
chore: update code base to fix bandit warnings

### PR DESCRIPTION
**Pull request by SMoraisAnsys**
As title says.

### CODE REVIEW

**Comment by SMoraisAnsys** [comment]
@klmcadams I saw this while working on pyaedt (I had some leftover after the tests overall the license checker haha)
I should start to work on #199 this week

**Comment by klmcadams** [comment]
@SMoraisAnsys Could you make a test case to show that it suppresses bandit warnings?

**Comment by SMoraisAnsys** [comment]
> @SMoraisAnsys Could you make a test case to show that it suppresses bandit warnings?

I'm not sure to understand what you mean by that. Like creating an empty repo with the modified file and a dedicated workflow to see the changes ?
Bellow are screenshots from bandit ouput (the first is the result from main branch, the second is the result from this PR)
image
image

**Comment by klmcadams** [comment]
Now I'm confused. I will message you

**Review by klmcadams — APPROVED** [review]

**Pull request merged**
